name: VelocityNavigator
version: '4.4.0'
main: com.demonz.velocitynavigator.bukkit.VelocityNavigatorBridge
api-version: '1.16'
authors: [DemonZDevelopment]
description: Backend inventory GUI bridge for VelocityNavigator.
